version: "3.4"

name: weatherapi
services:
  fastapi-app:  # nosemgrep
    image: ghcr.io/${GITHUB_REPOSITORY}:${TAG}
    container_name: ${container_name}
    ports:
      - "8000:8000"
    environment:
      - DOMAIN=${DOMAIN}
    restart: always
    networks:
      - weatherapi

networks:
  weatherapi:
    name: weatherapi
