version: '3'

services:
  python-3.9:  # nosemgrep
    image: mcr.microsoft.com/devcontainers/python:3.9
    container_name: $USER-python-3.9-weatherapi
    volumes:
      - ../../:/workspaces/weatherapi:cached
    command: sleep infinity
    env_file:
      - ../devcontainer.env
    platform: linux/amd64
    networks:
      - weatherapi-network

networks:
  weatherapi-network:
    name: "${USER}-weatherapi-network"
